// RankOps master checklist — ported from the Fleet SEO Tracker.
// 20 categories, 208 items. Item states are tracked per site in the store;
// this module is the immutable template every site is audited against.
// Item shape: { id, label, hint, crit }  —  crit = counts against health while pending.

export const CRITICAL = new Set(["f7","f4","t1","t8","n1","n4","c7","l1","s7","m5","uc1","x1","cp1","cp24"]);

export const HINTS = {
  "f4": "Done = no two categories cover the same product set; losers merged into winners and old URLs 301-redirected.",
  "f7": "Done = every product & category page outputs a correct self-referencing canonical tag (spot-check several).",
  "t1": "Done = ALL six pages exist and are live: Age Verification, Responsible Vaping, Shipping, Returns, Privacy, Terms. One missing = not done.",
  "t8": "Done = every admin-level account shows a real person or brand name publicly — no raw emails, no 'admin', no random strings.",
  "n1": "Done = the product's brand page exists on this store before the product goes live.",
  "n4": "Done = nicotine strength and other regulated specs verified against UAE rules (20mg/ml cap) before publish.",
  "c7": "Done = confirmed no existing page already targets this keyword/intent before publishing.",
  "l1": "Done = internal link report shows zero orphan pages — every published URL has at least one real inbound link.",
  "s7": "Done = schema passes Google Rich Results Test / Rank Math validation with zero errors.",
  "m5": "Done = pages with zero impressions after 28+ days reviewed for orphaned links or indexing issues.",
  "uc1": "Done = every live SKU checked against the UAE 20mg/ml nicotine cap; violations pulled, corrected, or formally flagged for a decision.",
  "x1": "Done = this store's meta titles/descriptions written uniquely — not copy-pasted from any sister store in the network.",
  "cp1": "Done = the fleet matrix names this store's role for this category (primary target for the head term, a distinct angle, or no investment) — recorded before any category content is built. Twenty look-alike category pages on twenty domains is the doorway pattern Google's spam policy names.",
  "cp24": "Done = robots.txt allows OAI-SearchBot, ChatGPT-User, ClaudeBot, PerplexityBot and Google-Extended, AND the Cloudflare AI-bot setting for this zone is set explicitly (not inherited) — re-checked after 15 Sep 2026, when Cloudflare's defaults flip to blocking on free-tier zones.",
  "bp20": "Done = the brand archive page itself (not just a linked guide) carries, below the product grid: buying-guide/spec bullets, a UAE-compliance paragraph with the correct cap + Federal Law 15/2009, a short FAQ, internal links to sibling brand/category/trust pages, and a WhatsApp link.",
  "cp30": "Done = the category archive page itself (not just a linked guide) carries, below the product grid: buying-guide/spec bullets, a UAE-compliance paragraph with the correct cap + Federal Law 15/2009, a short FAQ, internal links to sibling category/brand/trust pages, and a WhatsApp link.",
};

export const CHECKLIST = [
  { id: "found", short: "Found", title: "Technical Foundation", items: [
    { id: "f1", label: "Platform + SEO plugin confirmed and configured (e.g. Rank Math Pro active, XML sitemaps on)", hint: "", crit: false },
    { id: "f2", label: "Sitemaps live and submitted in Search Console (main, product, category/brand, post)", hint: "", crit: false },
    { id: "f3", label: "No stray legacy permalink prefixes hardcoded into internal links", hint: "", crit: false },
    { id: "f4", label: "Duplicate or overlapping categories merged with 301s", hint: "Done = no two categories cover the same product set; losers merged into winners and old URLs 301-redirected.", crit: true },
    { id: "f5", label: "Thin or duplicate brand and category archives pruned or noindexed", hint: "", crit: false },
    { id: "f6", label: "Post-revision bloat capped and old revisions purged", hint: "", crit: false },
    { id: "f7", label: "Canonical tags correct on every product, category and variation URL", hint: "Done = every product & category page outputs a correct self-referencing canonical tag (spot-check several).", crit: true },
    { id: "f8", label: "Sitewide broken-link / 404 audit run and fixed", hint: "", crit: false },
    { id: "f9", label: "Core Web Vitals and mobile-friendliness checked", hint: "", crit: false },
  ]},
  { id: "trust", short: "Trust", title: "E-E-A-T & Trust Pages", items: [
    { id: "t1", label: "Tier 1 policy pages live: Age Verification, Responsible Vaping, Shipping, Returns, Privacy, Terms", hint: "Done = ALL six pages exist and are live: Age Verification, Responsible Vaping, Shipping, Returns, Privacy, Terms. One missing = not done.", crit: true },
    { id: "t2", label: "About page names a real founder or expert with role and bio — no fake team", hint: "", crit: false },
    { id: "t3", label: "Contact page has working real contact methods, no broken form shortcodes", hint: "", crit: false },
    { id: "t4", label: "FAQ page built from real policy-backed Q&As, wired into nav/footer", hint: "", crit: false },
    { id: "t5", label: "Author / editorial entity page live with expertise and an editorial-standards statement", hint: "", crit: false },
    { id: "t6", label: "Product-page trust block present: reviewer byline, last-reviewed date, 18+/nicotine disclaimer", hint: "", crit: false },
    { id: "t7", label: "All trust-page internal links verified against the live sitemap — zero dead links", hint: "", crit: false },
    { id: "t8", label: "CMS author identity is a real name, not \"admin\"", hint: "Done = every admin-level account shows a real person or brand name publicly — no raw emails, no 'admin', no random strings.", crit: true },
    { id: "t9", label: "Footer/nav links wired to live pages, no dead # placeholders", hint: "", crit: false },
  ]},
  { id: "cluster", short: "Cluster", title: "Topical Architecture — Hub / Bridge / Spoke", items: [
    { id: "c1", label: "Topical map drafted per brand or category before content is produced", hint: "", crit: false },
    { id: "c2", label: "Hub (pillar) page defined per topic with a clear content scope", hint: "", crit: false },
    { id: "c3", label: "Spoke posts planned — reviews, guides, comparisons, 5–8 per hub", hint: "", crit: false },
    { id: "c4", label: "Bridge posts defined to connect hub, spokes and adjacent clusters", hint: "", crit: false },
    { id: "c5", label: "Five-link contract enforced on every new post (hub↔spoke, sibling, product, bridge)", hint: "", crit: false },
    { id: "c6", label: "Cross-cluster link slots identified and filled once the target hub goes live", hint: "", crit: false },
    { id: "c7", label: "Cannibalization check run before publishing — no overlap with an existing page's intent", hint: "Done = confirmed no existing page already targets this keyword/intent before publishing.", crit: true },
    { id: "c8", label: "Legacy overlapping posts 301-redirected into the new pillar", hint: "", crit: false },
    { id: "c9", label: "Cluster spokes prioritized by opportunity — demand (impressions) × current ranking weakness — not chosen arbitrarily", hint: "", crit: false },
    { id: "c10", label: "Each spoke defined with its own target query, intent and build-order priority before any brief is written", hint: "", crit: false },
    { id: "c11", label: "Thin-catalog gaps flagged separately from content gaps — a weak brand/category page with too few SKUs gets a stocking decision, not a content brief", hint: "", crit: false },
  ]},
  { id: "topicalmap", short: "Topical Map", title: "Topical Map v2 — Demand-Grounded & Live-Reconciled", items: [
    { id: "tm1", label: "Inputs gathered BEFORE any map is generated: live category list with product counts, brand list with product counts, every published page/post title + URL, and the top-200 GSC queries (impressions / clicks / avg position, 90 days) — no map built from guesses or a template category set", hint: "", crit: false },
    { id: "tm2", label: "Live-site reconciliation done: every proposed pillar/cluster checked against existing pages and categories — an existing page or category becomes the node (fold-into-live) and gets expanded; never a competing new URL on the same intent", hint: "", crit: false },
    { id: "tm3", label: "Pillars weighted by demand: ranked by GSC theme impressions × current ranking weakness, node count per theme proportional to real demand — trust/legal/authenticity kept as an E-E-A-T + AI-answer layer (one merged pillar, few spokes), never dozens of nodes on a theme with near-zero impressions", hint: "", crit: false },
    { id: "tm4", label: "Head-term family owned: the store/local intent (vape shop [city] / near me / vape store [country] / buy vape online) has its own pillar plus a physical-store page with LocalBusiness schema where a store exists — delivery, payment and ordering are clusters under it, not the pillar", hint: "", crit: false },
    { id: "tm5", label: "Brand & product tier present: a brands directory hub, brand cluster hubs ranked by demand × stock (built per the Brand Page category), and every existing product review attached as Tier 4 under its brand hub and cross-linked from the relevant cluster", hint: "", crit: false },
    { id: "tm6", label: "Full catalogue coverage: every category the store actually sells has a node — including heated tobacco, nicotine pouches, batteries/accessories, replacement pods & coils — nothing the catalogue carries is orphaned by the map", hint: "", crit: false },
    { id: "tm7", label: "Thin-stock separation: brands/categories with proven GSC demand but few or no SKUs listed as stocking decisions for the owner, not as content nodes (content cannot fix an empty archive)", hint: "", crit: false },
    { id: "tm8", label: "B2B/wholesale, zero-nicotine and other intents that GSC shows as real demand pools promoted to their own hubs, not buried as a single spoke", hint: "", crit: false },
    { id: "tm9", label: "Cannibalization pass run on the map ITSELF: zero duplicate slugs, zero duplicate keyword targets, every semantic-overlap group merged to one named survivor — the generator's own \"cannibalization risk: false\" flag is never trusted", hint: "", crit: false },
    { id: "tm10", label: "Synonym coverage handled on-page: e-cigarette / electronic cigarette, e-shisha / hookah-style, refillable, etc. added as H2/FAQ/schema wording inside the owning pillar — not spun into separate pages", hint: "", crit: false },
    { id: "tm11", label: "Local-language layer decided from data: Arabic-script (or other) GSC queries counted and bucketed by intent; one test landing page with hreflang before any scaling; brand names kept in Latin script; product images + Product schema treated as the surface for image/AI-mode conversational queries", hint: "", crit: false },
    { id: "tm12", label: "Emirate/city modifiers (Abu Dhabi, Sharjah, Ajman…) mapped to landing pages only where GSC demand or a real store/delivery zone justifies it — real shipping zones and store addresses pulled from the live store settings, not assumed", hint: "", crit: false },
    { id: "tm13", label: "Regulatory vocabulary verified on every node: MoIAT/ECAS (not ESMA); 20 mg/mL e-liquid cap kept separate from the ~16.6 mg/pouch cap; FTA digital tax stamp scope stated correctly (cigarettes / waterpipe / heated tobacco — not vapes or e-liquids); DET not DED; 100% excise + 5% VAT; no \"certified\" claim for any above-cap product; unverifiable third-party claims (couriers, BNPL providers, competitor shops) dropped", hint: "", crit: false },
    { id: "tm14", label: "Medical / YMYL framing stripped: no symptom diagnosis, taper schedules or cessation advice — strength guidance is product-led (which SKU/mg to buy) and carries the site's standard health disclaimer", hint: "", crit: false },
    { id: "tm15", label: "Supporting-page layer balanced: every pillar has its FAQ/long-tail layer built from real GSC long-tail, none left at zero; supporting pages that answer the same question as their cluster are merged into it as sections", hint: "", crit: false },
    { id: "tm16", label: "Generator-artefact check passed: no template leakage (wrong entity classes such as SkinConcern/Routine), no identical boilerplate across pillars, featured-snippet / bridge flags used selectively, stale hard-coded figures (SKU counts, catalogue size) replaced with live counts", hint: "", crit: false },
    { id: "tm17", label: "Per-node action recorded for every node — KEEP / REWRITE / MERGE / FOLD-INTO-LIVE / PROMOTE / DROP / CONDITIONAL — each with a named survivor node or live URL, a v2 pillar and a one-line reason; total word budget recomputed after merges", hint: "", crit: false },
    { id: "tm18", label: "Phased build order set by demand with a page/word budget per phase; legacy thin posts refreshed or 301-redirected into the nearest v2 node; 4-tier structure (pillar → cluster → supporting → product review) written down", hint: "", crit: false },
    { id: "tm19", label: "Owner decisions listed before writing starts (compliance position on above-cap products, stocking gaps, upcoming store openings, category merges, whether bundles/multi-packs exist) and the map re-checked against GSC at 3 months", hint: "", crit: false },
  ]},
  { id: "newprod", short: "New product", title: "New Product Page Upload", items: [
    { id: "n1", label: "Brand page confirmed to exist before upload — hard stop if missing", hint: "Done = the product's brand page exists on this store before the product goes live.", crit: true },
    { id: "n2", label: "Competitor source fully de-branded: name, links, SKU, store branding stripped", hint: "", crit: false },
    { id: "n3", label: "Own price used, not carried over from the source unless policy says otherwise", hint: "", crit: false },
    { id: "n4", label: "Specs verified against the UAE nicotine cap and other regulatory facts", hint: "Done = nicotine strength and other regulated specs verified against UAE rules (20mg/ml cap) before publish.", crit: true },
    { id: "n5", label: "Fabricated claims and empty stub sections stripped, nothing invented", hint: "", crit: false },
    { id: "n6", label: "In-catalogue comparison product selected — same family, adjacent tier, in stock", hint: "", crit: false },
    { id: "n7", label: "Quick-facts box and a distinct key-takeaways box included", hint: "", crit: false },
    { id: "n8", label: "FAQ section written and FAQPage schema added", hint: "", crit: false },
    { id: "n9", label: "Product, Review and BreadcrumbList schema added", hint: "", crit: false },
  ]},
  { id: "rewrite", short: "Rewrite", title: "Existing Product Page Rewrite", items: [
    { id: "r1", label: "GSC query export pulled as input", hint: "", crit: false },
    { id: "r2", label: "Every real query family answered somewhere on the page (FAQ as catch-all)", hint: "", crit: false },
    { id: "r3", label: "Query-coverage map produced", hint: "", crit: false },
    { id: "r4", label: "Stray competitor or off-site links removed", hint: "", crit: false },
    { id: "r5", label: "Meta title/description rewritten only where GSC data supports it", hint: "", crit: false },
    { id: "r6", label: "Cannibalization / sibling-tier check run, 301 noted if needed", hint: "", crit: false },
    { id: "r7", label: "Boilerplate stripped so the page reads as unique content", hint: "", crit: false },
  ]},
  { id: "brief", short: "Brief", title: "Content Brief & Blog Article", items: [
    { id: "b1", label: "Target keyword and search intent defined", hint: "", crit: false },
    { id: "b2", label: "Primary keyword plus semantic/entity keywords listed", hint: "", crit: false },
    { id: "b3", label: "Competitor and AI-answer content-gap check run", hint: "", crit: false },
    { id: "b4", label: "Outline mapped to intent — H1 through H3 structure", hint: "", crit: false },
    { id: "b5", label: "Quick-facts / key-takeaways box planned", hint: "", crit: false },
    { id: "b6", label: "Internal-linking plan set before writing — hub, sibling, bridge targets", hint: "", crit: false },
    { id: "b7", label: "Authoritative external source(s) identified for E-E-A-T linking", hint: "", crit: false },
    { id: "b8", label: "Author byline, reviewed-by and last-updated date assigned", hint: "", crit: false },
    { id: "b9", label: "Refresh / update review scheduled", hint: "", crit: false },
    { id: "b10", label: "Entity/co-occurrence map built — each semantic term assigned to the exact section it belongs in, not stuffed for coverage", hint: "", crit: false },
    { id: "b11", label: "Question bank mined from competitor/PAA-style research; final FAQ picks made from real options, not invented at draft time", hint: "", crit: false },
    { id: "b12", label: "Accuracy audit run BEFORE the outline — every figure classed (unsourced market figure / range-as-average / non-reconstructable / undated-unjurisdictioned regulatory claim / metric conflation / negative third-party claim), BLOCKERs listed, page marked PUBLICATION BLOCKED until they clear", hint: "", crit: false },
    { id: "b13", label: "Value register built — every number the page uses (body, boxes, table, FAQ, schema, meta) with its metric, source and as-of date; illustrative figures labelled as examples; puff counts marked rated vs measured; nicotine always in mg/mL", hint: "", crit: false },
    { id: "b14", label: "Metric dictionary written and the no-cross-metric rule applied — rated vs real puffs, mg/mL vs % vs mg/pouch, coil Ω vs wattage, device price vs cost-per-puff vs monthly running cost, delivery legs (cut-off → dispatch → door) stated separately", hint: "", crit: false },
    { id: "b15", label: "Open placeholders kept in ONE [TO VERIFY: what — where to get it] list (incl. author / reviewer / dates); none resolved with a plausible guess", hint: "", crit: false },
    { id: "b16", label: "Superlatives and volume claims cut or narrowed (\"#1 in Dubai\", \"best-selling\", \"cheapest in UAE\", \"everyone is switching\") unless first-party data is published with its method", hint: "", crit: false },
    { id: "b17", label: "Semantic scope fenced — entity graph with parent / children / siblings (named, never absorbed) / supporting entities with mention caps / EXCLUDED entities with reasons; article-cluster-site boundaries and a stated topical ceiling; predicates the writer must state in prose", hint: "", crit: false },
    { id: "b18", label: "Intent census with split decision (section on this page vs spoke vs compressed table) and attribute filtration with explicit REJECTs and reasons; word range derived from retained intents (~350 words each), not picked", hint: "", crit: false },
    { id: "b19", label: "Every H2 specified, not described — format + ranking signal, ≤40-word extractive answer, new aspect, predicates to establish, evidence tier, information-gain type, length band, fact-or-opinion claim basis; structure lock Claim → Mechanism → Evidence → Application; fact and opinion never in one paragraph", hint: "", crit: false },
    { id: "b20", label: "At least one uniqueness addition built from FIRST-PARTY store data (what customers actually buy, measured puff/battery tests, real delivery times by zone, stock depth), mapped to an H2 with why competitors and sibling stores miss it", hint: "", crit: false },
    { id: "b21", label: "Internal-link table carries anchor text, funnel stage, exact placement and role for every outbound link; INBOUND links named so the page is never an orphan; no product CTA before the first informational payload; disclosure above the first commercial link", hint: "", crit: false },
    { id: "b22", label: "Trust block complete — author, a DISTINCT reviewer with a checkable credential on nicotine-strength / legality pages, data-collected window for any first-party figure, published / last-updated / next-review dates, health-disclaimer link", hint: "", crit: false },
    { id: "b23", label: "Brief emits its AI control locks (structure lock, entity throttle, lexical injection list, length anchors, claim boundary in/out of scope) and a ready-to-paste writing prompt derived from the brief itself", hint: "", crit: false },
    { id: "b24", label: "Output audit run on the draft before publish — excluded-entity check, required-lexical check, depth verification (new aspect per H2, tables show inputs/operation/assumption, no ceiling crossed, every figure matches the value register, every [TO VERIFY] still visible and gating, every regulatory sentence jurisdiction-scoped and dated, every paragraph wholly fact or wholly opinion)", hint: "", crit: false },
  ]},
  { id: "brandpage", short: "Brand Pg", title: "Brand Page Content Cluster (UAE)", items: [
    { id: "bp1", label: "Brand hub page confirmed to exist before any spoke content is built — hard stop and flag if missing", hint: "", crit: false },
    { id: "bp2", label: "Product grid + intra-brand SKU comparison table (type/strength/capacity/price/stock) pulled live from the catalog, not hand-maintained", hint: "", crit: false },
    { id: "bp3", label: "Cross-store duplicate-content and scraping/plagiarism exposure checked for this brand across sibling fleet stores", hint: "", crit: false },
    { id: "bp4", label: "Site-architecture check — brand page reachable within a couple of clicks from homepage/nav, not buried", hint: "", crit: false },
    { id: "bp5", label: "UAE regulatory facts reverified before publishing any compliance claim — correct cap for the product type (20mg/mL e-liquid/disposable vs ~16.6mg/pouch, don't conflate), ECAS/MoIAT certification, FTA digital tax stamp, 18+ e-ID verification", hint: "", crit: false },
    { id: "bp6", label: "English + Arabic/transliterated keyword layer researched; hreflang planned if a localized Arabic page is built", hint: "", crit: false },
    { id: "bp7", label: "Search intent bucketed (transactional/informational/comparison/review/trust-compliance) with an AI-answer gap check specifically for UAE legality/nicotine questions", hint: "", crit: false },
    { id: "bp8", label: "Hub page carries a compliance/trust block, an authenticity/authorized-retailer line, and an emirate-level delivery note — not generic 'why buy from us' filler", hint: "", crit: false },
    { id: "bp9", label: "Hub page carries AggregateRating only if real reviews exist, and a video slot where available — no fabricated ratings", hint: "", crit: false },
    { id: "bp10", label: "Exactly 3 spokes planned per cluster (hero review, guide, comparison vs a named competitor), each with its own keyword, intent, word count and schema type", hint: "", crit: false },
    { id: "bp11", label: "Bridge-layer compliance content (UAE vaping-law/nicotine-cap explainer) identified or reused rather than duplicated per brand", hint: "", crit: false },
    { id: "bp12", label: "Hub↔spoke↔bridge link matrix built with varied anchor text — no repeated exact-match anchors", hint: "", crit: false },
    { id: "bp13", label: "Schema set per page (Brand/Organization+ItemList+FAQPage on hub, Review/FAQPage/Article per spoke) and full Product/Offer data (price, availability, shipping, return policy) on every linked product", hint: "", crit: false },
    { id: "bp14", label: "Build order followed — hub with its compliance block first; compliance/bridge content moved up if the AI-gap check found wrong legal answers", hint: "", crit: false },
    { id: "bp15", label: "Low-friction WhatsApp (or equivalent) contact path present on the hub and each spoke", hint: "", crit: false },
    { id: "bp16", label: "Off-page targets queued (manufacturer retailer listing, UAE directory/review-site presence, sameAs entity links) into the off-page category rather than left stranded in the plan", hint: "", crit: false },
    { id: "bp17", label: "Consistent author/reviewer identity with Person/Organization schema applied across the whole cluster", hint: "", crit: false },
    { id: "bp18", label: "Ranking-position goal set per piece before publish, checked at 4–6 weeks and 3 months; GA4 events tracked per cluster if available", hint: "", crit: false },
    { id: "bp19", label: "Quarterly AI-answer gap re-check and regulatory-figure re-verification scheduled; duplicate-content/compliance flags re-checked whenever the brand's product list changes", hint: "", crit: false },
    { id: "bp20", label: "Bottom-of-listing SEO content block published below the product grid — a buying-guide/spec-bullet section for this brand's product type, a UAE-compliance paragraph (correct nicotine cap for the type, Federal Law 15/2009 age-18 requirement), and a short FAQ — with internal links to sibling brand/category/trust pages and a WhatsApp link, matching the fleet template", hint: "Done = the brand archive page itself (not just a linked guide) carries, below the product grid: buying-guide/spec bullets, a UAE-compliance paragraph with the correct cap + Federal Law 15/2009, a short FAQ, internal links to sibling brand/category/trust pages, and a WhatsApp link.", crit: false },
  ]},
  { id: "catpage", short: "Cat Pg", title: "Category Page Content Cluster (UAE)", items: [
    { id: "cp1", label: "Fleet category-ownership recorded — this store's role for the category (primary target for the head term, a distinct angle such as budget/premium/Arabic-first/pouch specialist, or no investment) set in the fleet matrix before content is built", hint: "Done = the fleet matrix names this store's role for this category (primary target for the head term, a distinct angle, or no investment) — recorded before any category content is built. Twenty look-alike category pages on twenty domains is the doorway pattern Google's spam policy names.", crit: true },
    { id: "cp2", label: "Category page confirmed live at /product-category/{slug}/ (hard stop if missing), one click from homepage/nav, and the minimum-catalog-size gate applied — a thin category gets a hub only, no spokes", hint: "", crit: false },
    { id: "cp3", label: "Category-naming overlap on this store resolved — no two categories competing for the same product set or intent", hint: "", crit: false },
    { id: "cp4", label: "Category intro/guide copy checked against every sibling store and rewritten for genuine distinctiveness — not near-identical fleet boilerplate", hint: "", crit: false },
    { id: "cp5", label: "Faceted/filter URLs canonicalized or noindex,follow; sitemap lists only canonical category/subcategory URLs; paginated pages carry unique titles/meta", hint: "", crit: false },
    { id: "cp6", label: "UAE nicotine cap mapped to this category's product type (20 mg/mL for e-liquids, disposables and pods per UAE.S 5030:2018, whose tank limits are 10 mL integrated / 50 mL refill — not the EU 2 mL figure; ~16.6 mg/pouch for nicotine pouches under their own resolution; shisha checked per product) and reverified before any compliance claim", hint: "", crit: false },
    { id: "cp7", label: "Keyword research done — category seed set, Arabic/transliterated layer (hreflang planned if localized), on-site search mining, intent bucketing, competitor category-page scan", hint: "", crit: false },
    { id: "cp8", label: "Semantic entity/attribute coverage map built for this category type (puff count, mAh, coil, nic salt vs freebase, draw type, PG/VG, pouch size…) and used in hub prose, filters and the table", hint: "", crit: false },
    { id: "cp9", label: "SERP-shape check (snippet / PAA / forum threads / video / AI Overview) and AI-answer gap check for 'best {category} in UAE' and legality queries run, and the plan adjusted to what holds the top of the page", hint: "", crit: false },
    { id: "cp10", label: "Keyword-cannibalization check run in GSC between this category hub and the brand hubs it links to; category owns category terms, brand hubs own branded terms", hint: "", crit: false },
    { id: "cp11", label: "Hub intro/guide prose meets the depth minimum (~300–500 substantive words in the category's own vocabulary) and follows the H1/H2 heading template — not a two-line intro on a grid", hint: "", crit: false },
    { id: "cp12", label: "Hub carries a 'shop by brand' block linking every brand hub in the category, plus a subcategory breakdown where one exists", hint: "", crit: false },
    { id: "cp13", label: "Hub carries a cross-brand best-of comparison table (top 5–8 SKUs, mobile-scrollable or stacked) — distinct from brand-hub intra-brand tables and from the comparison spoke", hint: "", crit: false },
    { id: "cp14", label: "Hub trust block present — compliance facts per cp6, authenticity/genuine-stock line, payment methods (COD if offered), delivery time, emirate-level delivery note", hint: "", crit: false },
    { id: "cp15", label: "First-party data block published on the hub (reorder rates, best-sellers by emirate, strength tier first-timers choose…) with a stated refresh date — data no competitor or sister store can copy", hint: "", crit: false },
    { id: "cp16", label: "Original store photography on the hub with descriptive filenames and attribute-vocabulary alt text — not manufacturer stock images only", hint: "", crit: false },
    { id: "cp17", label: "Live stock handling — out-of-stock items badged or moved to the end of the grid, never mixed in at random", hint: "", crit: false },
    { id: "cp18", label: "AggregateRating shown only from real reviews; where none exist yet, a post-delivery WhatsApp/email review-request loop is running and checked monthly", hint: "", crit: false },
    { id: "cp19", label: "Exactly 3 spokes planned — best-of (reviews-system aligned: stated criteria, first-hand evidence, pros and cons, dated), buying guide, cross-brand comparison — each with keyword, intent, word count, schema", hint: "", crit: false },
    { id: "cp20", label: "Bridge-layer posts (UAE law / nicotine cap / where-you-can-vape) reused from the brand clusters, not duplicated per category", hint: "", crit: false },
    { id: "cp21", label: "Linking hierarchy verified both directions (category ↔ brand hub ↔ spokes), sibling-category cross-links where relevant, breadcrumb schema matches, related-guides module live", hint: "", crit: false },
    { id: "cp22", label: "Schema set — CollectionPage + ItemList + BreadcrumbList + FAQPage (+ AggregateRating if real); full Product/Offer data on every linked product", hint: "", crit: false },
    { id: "cp23", label: "Core Web Vitals on the grid — images lazy-loaded below the fold, real pagination or load-more instead of rendering the whole catalog, checked on mobile", hint: "", crit: false },
    { id: "cp24", label: "AI-crawler access confirmed — robots.txt allows answer-engine bots and the Cloudflare AI-bot setting is set explicitly for this zone (re-check after 15 Sep 2026)", hint: "Done = robots.txt allows OAI-SearchBot, ChatGPT-User, ClaudeBot, PerplexityBot and Google-Extended, AND the Cloudflare AI-bot setting for this zone is set explicitly (not inherited) — re-checked after 15 Sep 2026, when Cloudflare's defaults flip to blocking on free-tier zones.", crit: true },
    { id: "cp25", label: "Low-friction WhatsApp CTA on hub and spokes; at least one outbound link to an authoritative source on the hub", hint: "", crit: false },
    { id: "cp26", label: "Off-page targets specific to category pages (UAE shop roundups, directories, shopping guides) queued into the off-page category", hint: "", crit: false },
    { id: "cp27", label: "Consistent author/reviewer identity with Person/Organization schema across the whole category cluster", hint: "", crit: false },
    { id: "cp28", label: "KPIs set — ranking target per piece (checked at 4–6 weeks and 3 months), GA4 add-to-cart and WhatsApp-click events from category pages, monthly GSC title/meta CTR loop", hint: "", crit: false },
    { id: "cp29", label: "Maintenance cadence running — quarterly AI-gap and faceted-URL re-checks, refresh ahead of DSF/Ramadan/National Day where demand spikes, regulatory re-verify twice a year, first-party data refreshed on schedule", hint: "", crit: false },
    { id: "cp30", label: "Bottom-of-listing SEO content block published below the product grid — a buying-guide/spec-bullet section for this category's product type, a UAE-compliance paragraph (correct nicotine cap for the type, Federal Law 15/2009 age-18 requirement), and a short FAQ — with internal links to sibling category/brand/trust pages and a WhatsApp link, matching the fleet template", hint: "Done = the category archive page itself (not just a linked guide) carries, below the product grid: buying-guide/spec bullets, a UAE-compliance paragraph with the correct cap + Federal Law 15/2009, a short FAQ, internal links to sibling category/brand/trust pages, and a WhatsApp link.", crit: false },
  ]},
  { id: "semantic", short: "Semantic", title: "Semantic SEO & Schema", items: [
    { id: "s1", label: "Content structured around entities and relationships, not just keywords", hint: "", crit: false },
    { id: "s2", label: "Person schema for author/reviewer with knowsAbout and sameAs", hint: "", crit: false },
    { id: "s3", label: "Organization schema in place", hint: "", crit: false },
    { id: "s4", label: "Product schema complete — price, availability, brand, rating", hint: "", crit: false },
    { id: "s5", label: "FAQPage schema verified against real on-page Q&A", hint: "", crit: false },
    { id: "s6", label: "BreadcrumbList schema on all deep pages", hint: "", crit: false },
    { id: "s7", label: "Schema validated with zero errors (Rich Results Test / Rank Math check)", hint: "Done = schema passes Google Rich Results Test / Rank Math validation with zero errors.", crit: true },
    { id: "s8", label: "Full schema JSON-LD written at draft time with real content — no placeholder fields left live at publish", hint: "", crit: false },
    { id: "s9", label: "HowTo schema added for any genuine step-by-step process content", hint: "", crit: false },
    { id: "s10", label: "Schema checked 1:1 against visible on-page text — every schema Q&A/step matches what's actually on the page", hint: "", crit: false },
  ]},
  { id: "offpage", short: "Off-page", title: "Off-Page SEO & Digital PR", items: [
    { id: "op1", label: "Backlink profile audited — referring domains, spammy/toxic links flagged, disavow considered", hint: "", crit: false },
    { id: "op2", label: "Digital PR / outreach targets identified for authoritative backlinks", hint: "", crit: false },
    { id: "op3", label: "Review-platform presence built (Google, Trustpilot) with real, unmanufactured ratings", hint: "", crit: false },
    { id: "op4", label: "Brand mentions monitored; unlinked mentions converted to links where possible", hint: "", crit: false },
    { id: "op5", label: "Competitor backlink gap analysis run", hint: "", crit: false },
    { id: "op6", label: "New content actively promoted off-site, not just published and left to be found", hint: "", crit: false },
  ]},
  { id: "local", short: "Local", title: "Local SEO & Google Business Profile", items: [
    { id: "lo1", label: "Google Business Profile claimed, verified and fully completed", hint: "", crit: false },
    { id: "lo2", label: "NAP (name/address/phone) consistent across site, GBP and directory listings", hint: "", crit: false },
    { id: "lo3", label: "Local categories, service areas and emirates coverage set correctly on GBP", hint: "", crit: false },
    { id: "lo4", label: "Local landing content reflects real delivery/service-area facts, no stale claims", hint: "", crit: false },
    { id: "lo5", label: "LocalBusiness schema matches GBP data", hint: "", crit: false },
    { id: "lo6", label: "Store listed on relevant local/regional directories", hint: "", crit: false },
  ]},
  { id: "image", short: "Image", title: "Image SEO", items: [
    { id: "im1", label: "Descriptive file names, not IMG_1234.jpg", hint: "", crit: false },
    { id: "im2", label: "Alt text written for every product and content image", hint: "", crit: false },
    { id: "im3", label: "Images compressed / served in modern formats without hurting quality", hint: "", crit: false },
    { id: "im4", label: "No stock imagery used where real product photography is expected (reviews, E-E-A-T)", hint: "", crit: false },
    { id: "im5", label: "Key product images discoverable — image sitemap or equivalent checked", hint: "", crit: false },
  ]},
  { id: "links", short: "Linking", title: "Internal Linking", items: [
    { id: "l1", label: "No orphan pages — every published page has a real inbound link", hint: "Done = internal link report shows zero orphan pages — every published URL has at least one real inbound link.", crit: true },
    { id: "l2", label: "Hub↔spoke links are bidirectional", hint: "", crit: false },
    { id: "l3", label: "Sibling-to-sibling links within the same cluster", hint: "", crit: false },
    { id: "l4", label: "Product↔blog cross-links in both directions", hint: "", crit: false },
    { id: "l5", label: "Cross-cluster mirror-pair links where relevant", hint: "", crit: false },
    { id: "l6", label: "Internal link report reviewed periodically via the SEO plugin", hint: "", crit: false },
  ]},
  { id: "aeo", short: "AEO", title: "AI Overview / AEO", items: [
    { id: "a1", label: "Page answers likely AI Overview / assistant queries directly and early", hint: "", crit: false },
    { id: "a2", label: "Structured Q&A blocks present for easy extraction", hint: "", crit: false },
    { id: "a3", label: "Claims are quantified, sourced and hands-on rather than vague", hint: "", crit: false },
    { id: "a4", label: "Unique photography or data used over stock imagery", hint: "", crit: false },
    { id: "a5", label: "Brand and product entity named consistently for citation", hint: "", crit: false },
    { id: "a6", label: "AI-visibility spot-check run for target queries", hint: "", crit: false },
    { id: "a7", label: "Domain confirmed eligible in Google's source preferences tool, then the Preferred Sources button installed sitewide (publisher.js in <head> + button div in a shared template)", hint: "", crit: false },
    { id: "a8", label: "Enumerable content (steps, signs, criteria) marked up as real lists/tables in the HTML, not prose paragraphs", hint: "", crit: false },
  ]},
  { id: "maint", short: "Maint.", title: "Post-Publish & Maintenance", items: [
    { id: "m1", label: "Indexing confirmed in Search Console after publish", hint: "", crit: false },
    { id: "m2", label: "Meta and schema verified live post-publish", hint: "", crit: false },
    { id: "m3", label: "Remaining cross-link slots filled once the page is live", hint: "", crit: false },
    { id: "m4", label: "28-day performance check — impressions, clicks, position", hint: "", crit: false },
    { id: "m5", label: "Zero-impression pages audited for orphaned internal links", hint: "Done = pages with zero impressions after 28+ days reviewed for orphaned links or indexing issues.", crit: true },
    { id: "m6", label: "Content-decay refresh review scheduled", hint: "", crit: false },
    { id: "m7", label: "Open legal/compliance flags logged and tracked", hint: "", crit: false },
  ]},
  { id: "sec", short: "Security", title: "Security & Site Hygiene", items: [
    { id: "sc1", label: "User registration closed or protected — no open spam signups", hint: "", crit: false },
    { id: "sc2", label: "Spam/bot accounts purged; only real staff accounts remain", hint: "", crit: false },
    { id: "sc3", label: "Debug display OFF in production — no PHP errors shown to visitors", hint: "", crit: false },
    { id: "sc4", label: "WordPress core, theme and key plugins up to date", hint: "", crit: false },
    { id: "sc5", label: "Working backup schedule in place and verified (e.g. UpdraftPlus)", hint: "", crit: false },
    { id: "sc6", label: "Admin accounts minimal, each with a real named identity", hint: "", crit: false },
  ]},
  { id: "comp", short: "Compliance", title: "UAE Compliance", items: [
    { id: "uc1", label: "Every live SKU verified against the UAE 20mg/ml nicotine cap", hint: "Done = every live SKU checked against the UAE 20mg/ml nicotine cap; violations pulled, corrected, or formally flagged for a decision.", crit: true },
    { id: "uc2", label: "Age-gate (18+) live and working on site entry", hint: "", crit: false },
    { id: "uc3", label: "Health / age disclaimers present sitewide (footer + product pages)", hint: "", crit: false },
    { id: "uc4", label: "Vaping-law and health-claim content under legal hold until signed off", hint: "", crit: false },
    { id: "uc5", label: "Business identity / licence info displayed on the site", hint: "", crit: false },
  ]},
  { id: "analytics", short: "Analytics", title: "Analytics & Measurement", items: [
    { id: "ga1", label: "GA4 property connected and receiving data", hint: "", crit: false },
    { id: "ga2", label: "Google Search Console verified and linked to Rank Math", hint: "", crit: false },
    { id: "ga3", label: "Rank Math Analytics / keyword tracking configured", hint: "", crit: false },
    { id: "ga4", label: "Rank Math AI Visibility brand created and tracking target queries", hint: "", crit: false },
    { id: "ga5", label: "Monthly SEO email report configured to the right inbox", hint: "", crit: false },
    { id: "ga6", label: "AI-visibility tracked WITHOUT Rank Math's paid tier (manual prompt-audit spreadsheet and/or GA4 AI-referral traffic check, run on a recurring cadence)", hint: "", crit: false },
  ]},
  { id: "xstore", short: "X-store", title: "Cross-Store Uniqueness", items: [
    { id: "x1", label: "Meta titles/descriptions unique vs sister stores — not copy-pasted", hint: "Done = this store's meta titles/descriptions written uniquely — not copy-pasted from any sister store in the network.", crit: true },
    { id: "x2", label: "About and policy page wording distinct from sister stores", hint: "", crit: false },
    { id: "x3", label: "Product descriptions differentiated across the network for shared SKUs", hint: "", crit: false },
    { id: "x4", label: "No cross-store duplicate blog posts targeting the same keyword", hint: "", crit: false },
    { id: "x5", label: "Distinct brand entity per store — name, logo, GBP where applicable", hint: "", crit: false },
  ]},
];

export const TOTAL_ITEMS = CHECKLIST.reduce((n, c) => n + c.items.length, 0);

/** id → { item, cat } for O(1) lookups from fix requests and logs. */
export const ITEM_INDEX = new Map();
for (const cat of CHECKLIST) for (const item of cat.items) ITEM_INDEX.set(item.id, { item, cat });

export function itemById(id) { return ITEM_INDEX.get(id) || null; }
