// End-to-end check of the running app. Usage:  npm run dev   (in another shell)   then   BASE_URL=http://127.0.0.1:8080 npm run e2e
// Needs:  npm i -D playwright  (and a Chromium it can launch).
import { chromium } from 'playwright';
const results = []; const ok = (name, cond, detail='') => { results.push([cond?'PASS':'FAIL', name, detail]); if(!cond) console.log('  ✗', name, detail); };
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', e => errors.push('pageerror: ' + e.message));
page.on('console', m => { if (m.type()==='error' && !/CERT|fonts\.g/.test(m.text())) errors.push('console: ' + m.text()); });
page.on('dialog', d => d.accept());
const st = () => page.evaluate(() => window.rankops.store.state);
const U = (process.env.BASE_URL || 'http://127.0.0.1:8080').replace(/\/$/, '') + '/index.html';

await page.goto(U); await page.waitForFunction(() => window.rankops && document.querySelectorAll('#dashboard-client-rows tr').length > 0);
let s = await st();
ok('demo seeded: 4 clients / 4 sites', Object.keys(s.clients).length===4 && Object.keys(s.sites).length===4);
const tiles = await page.evaluate(() => ({ h: +document.getElementById('tile-health').textContent, sites: +document.getElementById('tile-sites').textContent, flags: +document.getElementById('tile-flags').textContent, req: +document.getElementById('tile-fixreq').textContent, done: +document.getElementById('tile-done').textContent }));
const expReq = Object.values(s.fixReqs).filter(r=>r.status!=='done').length;
ok('tiles derive from state', tiles.sites===4 && tiles.flags===7 && tiles.req===expReq && tiles.done===3 && tiles.h>0, JSON.stringify(tiles)+' expReq='+expReq);
ok('every dashboard row is clickable with a handler', await page.$$eval('#dashboard-client-rows tr', rs => rs.every(r => r.dataset.action==='open-client-primary')));
ok('nav Clients count = 4', (await page.textContent('#count-clients')).trim()==='4');
ok('nav Flags count = 7', (await page.textContent('#count-flags')).trim()==='7');
ok('sidebar lists 4 sites', (await page.$$('#nav-sites .site-link')).length===4);
await page.fill('#client-search', 'shopify');
ok('search matches by platform', (await page.$$('#dashboard-client-rows tr')).length===1);
await page.fill('#client-search', 'zzz');
ok('search empty state shown', await page.isVisible('#dashboard-empty'));
await page.fill('#client-search', '');
ok('high flag in Needs Your Decision', (await page.$$('#dash-decisions .flag-row')).length===1);
await page.click('#dashboard-client-rows tr:nth-child(2)');
ok('row click opens site view', await page.$eval('.view.active', v => v.id)==='view-site');
ok('hash routing set', (await page.evaluate(() => location.hash)).startsWith('#/site/'));
await page.click('.site-link[data-site="s_vapewizard"]');
ok('site header name', (await page.textContent('#site-name')).trim()==='Vape Wizard DXB');
const prog = await page.textContent('#site-progress');
{ const it = s.sites.s_vapewizard.items; const na = Object.values(it).filter(v=>v==='na').length, done = Object.values(it).filter(v=>v==='done').length;
  ok('progress reads done / (208 − n/a)', prog.trim()===`${done} / ${208-na} items · ${na} n/a`, prog); }
const health0 = await page.textContent('#site-health');
ok('tab counters live', (await page.textContent('#tab-count-fixreq')).trim()==='(5)' && (await page.textContent('#tab-count-flags')).trim()==='(4)', `${await page.textContent('#tab-count-fixreq')} ${await page.textContent('#tab-count-flags')}`);
ok('20 category cards', (await page.$$('#checklist-cats .cat')).length===20);
await page.click('.cat[data-cat="found"] .cat-head');
ok('category toggles open', await page.$eval('.cat[data-cat="found"]', c => c.classList.contains('open')));
const beforeF4 = await page.$eval('.item[data-item="f4"] .state-btn', b => b.dataset.state);
await page.click('.item[data-item="f4"] .state-btn');
s = await st();
ok('f4 pending → done persisted in state', beforeF4==='pending' && s.sites.s_vapewizard.items.f4==='done');
ok('done item shows evidence link button', await page.isVisible('.item[data-item="f4"] .ev-btn'));
ok('open fix request for f4 auto-closed', s.fixReqs.r_f4.status==='done');
ok('category still open after re-render', await page.$eval('.cat[data-cat="found"]', c => c.classList.contains('open')));
const health1 = await page.textContent('#site-health');
ok('health recomputed after change', health0 !== health1, `${health0} → ${health1}`);
await page.click('.item[data-item="f4"] .ev-btn');
await page.fill('[data-evidence-input][data-item="f4"]', 'https://example.com/proof');
await page.keyboard.press('Enter');
s = await st();
ok('evidence URL saved on Enter', s.sites.s_vapewizard.evidence.f4.url==='https://example.com/proof');
ok('evidence link rendered', await page.isVisible('.item[data-item="f4"] a[href="https://example.com/proof"]'));
await page.click('.item[data-item="f4"] .state-btn'); s = await st(); ok('checkbox toggles done → pending (never to n/a)', !('f4' in s.sites.s_vapewizard.items));
await page.click('.item[data-item="f4"] [data-action="item-na"]'); s = await st(); ok('n/a only via its own button', s.sites.s_vapewizard.items.f4==='na');
await page.click('.item[data-item="f4"] .state-btn'); s = await st(); ok('ticking an n/a item makes it applicable again', !('f4' in s.sites.s_vapewizard.items));
await page.click('.item[data-item="f4"] .fix-btn');
ok('fix modal opens', await page.$eval('#fix-modal', m => m.classList.contains('open')));
await page.selectOption('#fix-priority', 'p0'); await page.fill('#fix-note', 'test note'); await page.keyboard.press('Control+Enter');
s = await st();
const newReq = Object.values(s.fixReqs).find(r => r.itemId==='f4' && r.status!=='done');
ok('fix queued via Enter with P0 + note', !!newReq && newReq.priority==='p0' && newReq.note==='test note');
ok('item row shows queued pill', await page.isVisible('.item[data-item="f4"] .pill.pending'));
await page.click('[data-action="checklist-filter"][data-filter="crit"]');
const critShown = await page.$$eval('#checklist-cats .item', els => els.length);
{ const expCrit = await page.evaluate(() => { const s = window.rankops.store.state.sites.s_vapewizard; let n=0; document.querySelectorAll('#templates-body'); return n; });
  const expC = await page.evaluate(async () => { const m = await import('./js/checklist.js'); const it = window.rankops.store.state.sites.s_vapewizard.items; return m.CHECKLIST.flatMap(c=>c.items).filter(i=>i.crit).length; });
  ok('critical filter shows every critical item, done or not', critShown===expC, `${critShown} vs ${expC}`); }
await page.click('[data-action="checklist-filter"][data-filter="all"]');
await page.click('.tab[data-sub="fixreq"]');
const kb = await page.evaluate(() => ['pending','progress','done'].map(c => [ +document.getElementById('kcount-'+c).textContent, document.querySelectorAll('#kcol-'+c+' .kcard').length ]));
ok('kanban counts == card counts', kb.every(([n,c]) => n===c), JSON.stringify(kb));
const l5PrioBefore = await page.$eval('.kcard[data-req="r_l5"] [data-fix-priority]', s => s.value);
await page.selectOption('.kcard[data-req="r_l5"] [data-fix-status]', 'in_progress');
s = await st();
ok('status change via select persisted', s.fixReqs.r_l5.status==='in_progress');
ok('priority preserved through status change (was P2)', l5PrioBefore==='p2' && s.fixReqs.r_l5.priority==='p2');
const kb2 = await page.evaluate(() => ['pending','progress','done'].map(c => [ +document.getElementById('kcount-'+c).textContent, document.querySelectorAll('#kcol-'+c+' .kcard').length ]));
ok('counts still == cards after move', kb2.every(([n,c]) => n===c) && kb2[1][0]===kb[1][0]+1, JSON.stringify(kb2));
await page.selectOption('.kcard[data-req="r_l5"] [data-fix-status]', 'done');
s = await st();
ok('fix → done marks item l5 done', s.sites.s_vapewizard.items.l5==='done');
ok('placeholder never counted', await page.evaluate(() => document.querySelectorAll('#kcol-pending .kcard').length === +document.getElementById('kcount-pending').textContent));
await page.click('.tab[data-sub="siteflags"]');
await page.fill('#flag-text', '<img src=x onerror="window.__XSS=1">Injected flag'); await page.selectOption('#flag-sev', 'high'); await page.keyboard.press('Enter');
await page.waitForTimeout(300);
ok('flag added', (await page.$$('#site-flags-list .flag-row')).length===5);
ok('XSS via flag text neutralised', !(await page.evaluate(() => window.__XSS)));
ok('flag text rendered escaped', (await page.textContent('#site-flags-list')).includes('<img src=x'));
const firstFlag = await page.$eval('#site-flags-list .flag-row [data-action="flag-resolve"]', b => b.dataset.flag);
await page.click(`[data-action="flag-resolve"][data-flag="${firstFlag}"]`);
s = await st(); ok('flag resolved', s.flags[firstFlag].resolved===true);
ok('tab flag count decremented', (await page.textContent('#tab-count-flags')).trim()==='(4)');
await page.click('.tab[data-sub="log"]');
const logN = (await page.$$('#audit-log-body .log-item')).length;
ok('audit log populated', logN > 10, String(logN));
ok('log has our f4 entry', (await page.textContent('#audit-log-body')).includes('f4 marked done'));
await page.click('#record-audit-btn');
ok('record audit stamps today', (await page.textContent('#site-audit')).trim()==='today');
await page.click('[data-action="edit-site"]');
await page.fill('#site-form-domain', 'https://www.NewDomain.com/path'); await page.click('#site-form-submit');
s = await st(); ok('site domain normalised + saved', s.sites.s_vapewizard.domain==='newdomain.com');
await page.click('.nav-item[data-view="flags"]');
s = await st();
ok('inbox lists open flags', (await page.$$('#flags-list .flag-row')).length===Object.values(s.flags).filter(f=>!f.resolved).length);
await page.click('[data-action="flags-filter"][data-filter="high"]');
ok('severity filter', (await page.$$('#flags-list .flag-row')).length===Object.values(s.flags).filter(f=>!f.resolved&&f.severity==='high').length);
await page.click('[data-action="flags-filter"][data-filter="all"]');
await page.check('#flags-show-resolved');
ok('show resolved adds resolved flag', (await page.$$('#flags-list .flag-row')).length===Object.keys(s.flags).length);
await page.uncheck('#flags-show-resolved');
await page.click('.nav-item[data-view="clients"]');
await page.click('#add-client-btn');
ok('client modal open + focused name', await page.evaluate(() => document.activeElement.id==='client-name'));
await page.keyboard.press('Escape');
ok('Escape closes modal', !(await page.$eval('#client-modal', m => m.classList.contains('open'))));
await page.click('#add-client-btn');
await page.fill('#client-name', '<b onmouseover=alert(1)>Zed</b> Motors'); await page.fill('#client-contact', 'Z. Zed'); await page.fill('#client-site-domain', 'zedmotors.ae');
await page.keyboard.press('Enter');
s = await st();
const zed = Object.values(s.clients).find(c => c.name.includes('Zed'));
ok('client + first site created via Enter', !!zed && Object.values(s.sites).some(x => x.clientId===zed.id && x.domain==='zedmotors.ae'));
ok('landed on new site checklist at 0 done', await page.$eval('.view.active', v=>v.id)==='view-site' && (await page.textContent('#site-progress')).trim().startsWith('0 / 208'));
ok('name rendered escaped (no <b> element)', (await page.$$('#site-name b')).length===0 && (await page.textContent('#site-name')).includes('<b onmouseover'));
await page.click('.nav-item[data-view="clients"]');
ok('clients table has 5 rows, all clickable', await page.$$eval('#clients-rows tr', rs => rs.length===5 && rs.every(r => r.dataset.action)));
await page.click('#theme-toggle'); s = await st(); ok('theme → dark', s.theme==='dark' && await page.evaluate(() => document.documentElement.dataset.theme==='dark'));
await page.click('#theme-toggle'); await page.click('#theme-toggle'); s = await st(); ok('theme cycles back to system', s.theme===null);
await page.click('.nav-item[data-view="templates"]');
ok('template lists 208 items', (await page.$$('#templates-body .tmpl-item')).length===208);
await page.fill('#tmpl-search', 'canonical');
const tm = (await page.$$('#templates-body .tmpl-item')).length;
ok('template search filters', tm>0 && tm<20, String(tm));
await page.fill('#tmpl-search', '');
await page.goto(U + '#/site/s_vapewizard/fixreq'); await page.waitForFunction(() => window.rankops && document.querySelector('.view.active'));
s = await st();
ok('state persisted across reload', s.sites.s_vapewizard.domain==='newdomain.com' && Object.keys(s.clients).length===5 && s.fixReqs.r_l5.status==='done');
ok('deep link opens site + tab', await page.$eval('.view.active', v=>v.id)==='view-site' && await page.$eval('.subview.active', v=>v.id)==='sub-fixreq');
await page.click('.nav-item[data-view="templates"]');
const [dl] = await Promise.all([page.waitForEvent('download'), page.click('[data-action="export"]')]);
ok('export downloads .json', (dl.suggestedFilename()||'').endsWith('.json'));
await page.click('.nav-item[data-view="clients"]');
await page.click(`[data-action="remove-client"][data-client="${zed.id}"]`);
s = await st(); ok('remove client cascades to its site', !s.clients[zed.id] && !Object.values(s.sites).some(x=>x.clientId===zed.id));
const a11y = await page.evaluate(() => ({ unlabeled: [...document.querySelectorAll('input:not([type=hidden]),select,textarea')].filter(i => !i.getAttribute('aria-label') && !(i.id && document.querySelector(`label[for="${i.id}"]`))).map(i=>i.id||i.outerHTML.slice(0,40)), dialogs: document.querySelectorAll('[role=dialog][aria-modal=true]').length, favicon: !!document.querySelector('link[rel=icon]') }));
ok('all inputs labelled', a11y.unlabeled.length===0, JSON.stringify(a11y.unlabeled));
ok('4 modals are dialogs; favicon present', a11y.dialogs===4 && a11y.favicon);
await page.setViewportSize({ width: 390, height: 800 }); await page.click('.nav-item[data-view="dashboard"]');
const sw = await page.evaluate(() => document.documentElement.scrollWidth);
ok('no horizontal overflow at 390px', sw <= 392, String(sw));
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto(U + '#/site/s_vapewizard/checklist'); await page.waitForFunction(() => document.querySelector('.view.active'));
await page.click('.cat[data-cat="found"] .cat-head'); await page.screenshot({ path: 'scripts/screenshot-site.png' });
await page.goto(U + '#/dashboard'); await page.waitForFunction(() => document.querySelectorAll('#dashboard-client-rows tr').length>0); await page.screenshot({ path: 'scripts/screenshot-dashboard.png' });
await browser.close();
ok('zero console/page errors', errors.length===0, errors.join(' | '));
const fails = results.filter(r => r[0]==='FAIL');
console.log(`\n${results.length - fails.length}/${results.length} checks passed`);
process.exitCode = fails.length ? 1 : 0;
